### PR TITLE
Add command to install mamba

### PR DESCRIPTION
**Pull request by jtpio**
Let's add commands one by one as needed.

### CODE REVIEW

**Comment by jtpio** [comment]
Next is to make the `mamba` command available to the next steps in the workflow: https://github.com/TheSnakePit/setup-mamba/pull/3/checks?check_run_id=739111507

**Comment by jtpio** [comment]
Some progress!

image

**Comment by jaimergp** [comment]
Re MacOS, `conda` is not in `PATH` in that OS. You can use `${CONDA}/condabin/conda` though.
I like @goanpeca's action for Miniconda - maybe there are some patterns there useful for this one too! https://github.com/goanpeca/setup-miniconda

**Comment by jtpio** [comment]
Thanks @jaimergp, will have a look!

**Comment by jaimergp** [comment]
If it helps, this is what I was using to initialize conda before I changed to goanpeca's action:

https://github.com/openkinome/kinoml/blob/master/devtools/scripts/initialize_conda.sh

**Comment by jtpio** [comment]
Thanks @jaimergp!

Looks like it's now passing on mac os after fixing the path and permissions.

For windows it might indeed be an issue with the activate script.

**Comment by jtpio** [comment]
So it looks like it's running on linux and mac os. Let's fix windows separately.

Thanks @jaimergp for the help. Don't hesitate to open new issues or a PR if you want to!

**Pull request merged**
